# Generated by Django 4.2.2 on 2023-08-01 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logicapp', '0002_product_sale_remove_enterprise_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b32759de-ee8b-4572-996d-a649e8a91183'), unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('81f31371-0c3b-4bc9-88c8-172522b0cd63'), unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c565f163-9d48-4dea-a2c3-dab3016d783f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sales_made',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('37d40be3-9467-496b-a403-24ece73ec6b1'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shoppingcar',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3f9428b2-569c-4ab3-a1e6-f04752f79a43'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='text_message',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('16c11f52-1a93-47bf-a02f-e89619b5e757'), primary_key=True, serialize=False, unique=True),
        ),
    ]
